### ISSUE TITLE
Remove swagger README transforms

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#11344]
The current generate code was generated with this readme:
`````
# Azure Search for Python

> see https://aka.ms/autorest

### Settings
```yaml
input-file: searchservice.json
output-folder: generated
namespace: azure.search.documents
no-namespace-folders: true
license-header: MICROSOFT_MIT_NO_VERSION
clear-output-folder: true
python: true
```

### Remove x-ms-pageable
Currently breaking the latest version of autorest.python
``` yaml
directive:
- from: swagger-document
  where: $["paths"]..get
  transform: >
    if ($["x-ms-pageable"]) { delete $["x-ms-pageable"]; }
```
`````

This removes `x-ms-pageable` and the reason is that some results need transformations on individual results, e.g. 
```
listize_synonyms(x)
```
before returning/yielding them.

 @lmazuel  mentions there will be a hook added that will make this transform unecessary

cc @xiangyan99 @heaths
