### ISSUE TITLE
 CheckPrivateLinkServiceVisibility api in network has changed

### ISSUE THREAD

**Issue by 00Kai0** [Azure/azure-sdk-for-python#11627]
```
request:
    body: '{"privateLinkServiceAlias": "mypls.00000000-0000-0000-0000-000000000000.azure.privatelinkservice"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '98'
      Content-Type:
      - application/json
      User-Agent:
      - azsdk-python-azure-mgmt-network/11.0.0 Python/3.6.9 (Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic)
    method: POST
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test_cli_mgmt_network_endpoint_test_network89b511ec/providers/Microsoft.Network/locations/eastus/checkPrivateLinkServiceVisibility?api-version=2020-04-01
  response:
    body:
      string: 'null'
    headers:
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operations/93d10632-9dba-4dab-9763-ec8705fbd40e?api-version=2020-04-01
      cache-control:
      - no-cache
      content-length:
      - '4'
      content-type:
      - application/json; charset=utf-8
      date:
      - Fri, 22 May 2020 09:37:48 GMT
      expires:
      - '-1'
      location:
      - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operationResults/93d10632-9dba-4dab-9763-ec8705fbd40e?api-version=2020-04-01
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-arm-service-request-id:
      - 746f965a-4c48-49ac-8842-55546ee5664e
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 202
      message: Accepted
```
This  [checkPrivateLinkServiceVisibility api](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/privatelinkservices/checkprivatelinkservicevisibility) returned an unexcepted code 202. I think it has been change to a LRO method, but hasn't been updated in swagger.
