### ISSUE TITLE
Changing Azure Storage to GRS turns off HTTPS Only

### ISSUE THREAD

**Issue by HarleyB123** [Azure/azure-sdk-for-python#12046]
- azure-mgmt-storage
- 10.0.0 (2020-05-07)
- Python 3.7

I have a script that changes all storage accounts from LRS to GRS replication. When looking at the change history actions, I can also see that it turns HTTPS Only to False.

1. When running this script:

```
#! /usr/bin/env python3
from azure.mgmt.storage import StorageManagementClient
from azure.mgmt.storage.models import StorageAccountUpdateParameters, Sku, SkuName


def list_storage_accounts(credentials, rgs):
    print("Fetching storage accounts data")
    storage_account_data = {}
    for sub, groups in rgs.items():
        storage_client = StorageManagementClient(credentials, sub)
        for rg in groups:
            storage_accounts = storage_client.storage_accounts.list_by_resource_group(
                rg
            )
            for account in storage_accounts:
                account_data = dict(
                    {
                        "name": account.name,
                        "sub": sub,
                        "resource_group": rg,
                        "sku": account.sku.name,
                    }
                )
                storage_account_data[account.name] = account_data

    return storage_account_data


def change_sku(credentials, storage_accounts):
    storage_container_data = {}
    for account, config in storage_accounts.items():
        storage_client = StorageManagementClient(credentials, config.get("sub"))
        storage_container_data[account] = account
        if (str(config.get("sku"))) == "SkuName.standard_lrs":
            storage_client.storage_accounts.update(
                config.get("resource_group"),
                account,
                StorageAccountUpdateParameters(sku=Sku(name=SkuName.standard_grs)),
            )
            print(f"Storage account {account} changed to standard_grs SKU")


def change_storage_sku(credentials, rgs):
    storage_accounts = list_storage_accounts(credentials, rgs)
    change_sku(credentials, storage_accounts)
```

You should then go to the change history of the bucket and see that both the storage account sku has change as well as "supportsHttpsTrafficOnly" if it was previously set to true.

**Expected behavior**
The change should be on LRS storage accounts to GRS, with no impact on HTTPS Only functionality.

**Screenshots**

<img width="830" alt="Screen Shot 2020-06-15 at 08 53 52" src="https://user-images.githubusercontent.com/25295682/84631883-08b4d000-aee6-11ea-871e-41efca9dff07.png">

**Comment by lmazuel** [comment]
Hi @HarleyB123 

The recommended pattern to update is to always do a GET first, to get the object as it is and change it. Otherwise, you will send default client value that are not default on the server, and see what you get. Something like this (written on the fly on this issue, not tested):

```python
def change_sku(credentials, storage_accounts):
    storage_container_data = {}
    for account, config in storage_accounts.items():
        storage_client = StorageManagementClient(credentials, config.get("sub"))
        storage_container_data[account] = account
        if (str(config.get("sku"))) == "SkuName.standard_lrs":
            storage_account = storage_client.storage_accounts.get(
                config.get("resource_group"),
                account,
            )
            storage_account.sku.name = SkuName.standard_grs
            storage_client.storage_accounts.update(
                config.get("resource_group"),
                account,
                storage_account,
            )
            print(f"Storage account {account} changed to standard_grs SKU")
```

@RodgeFu @changlong-liu @zikalino I realize the sample I wrote was not taking this into account, and this should be updated:
https://github.com/Azure-Samples/storage-python-manage/blob/bedff59adbdc7dc142c4cdd44c0237a94a50153a/example.py#L125-L133

**Comment by 00Kai0** [comment]
Hi @HarleyB123 , I tried with 10.0.0, but didn't get this problem.
Here is the test code:
```
        # StorageAccountCreate[put]
        storageAccount = {
          "sku": {
            "name": "Standard_LRS"
          },
          "kind": "StorageV2",
          "location": "westeurope",
          "encryption": {
            "services": {
              "file": {
                "key_type": "Account",
                "enabled": True
              },
              "blob": {
                "key_type": "Account",
                "enabled": True
              }
            },
            "key_source": "Microsoft.Storage"
          },
          "tags": {
            "key1": "value1",
            "key2": "value2"
          },
          "enable_https_traffic_only": True  # enable https traffic only
        }
        result = self.mgmt_client.storage_accounts.create(resource_group.name, STORAGE_ACCOUNT_NAME, storageAccount)
        result = result.result()

        from azure.mgmt.storage.models import StorageAccountUpdateParameters, Sku, SkuName

        accountUpdate = StorageAccountUpdateParameters(sku=Sku(name=SkuName.standard_grs))
        result = self.mgmt_client.storage_accounts.update(resource_group.name, STORAGE_ACCOUNT_NAME, accountUpdate)

        time.sleep(30)
        account = self.mgmt_client.storage_accounts.get_properties(resource_group.name, STORAGE_ACCOUNT_NAME)
        assert result.enable_https_traffic_only is True
```

Can you show more useful info?

**Comment by HarleyB123** [comment]
Hi @00Kai0 - thanks for this.

I have tried altered my script so that it prints out the properties either side of the update. Below is my console output:

```yaml
{
'additional_properties': {}, 
'id':'/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Storage/storageAccounts/<REDACTED>', 
'name': '<REDACTED>', '
type': 'Microsoft.Storage/storageAccounts', 
'tags': {}, 
'location': 'ukwest', 
'sku': <azure.mgmt.storage.v2018_02_01.models.sku_py3.Sku object at 0x109113790>, 
'kind': <Kind.storage_v2: 'StorageV2'>, 
'identity': None, 
'provisioning_state': <ProvisioningState.succeeded: 'Succeeded'>, 
'primary_endpoints': <azure.mgmt.storage.v2018_02_01.models.endpoints_py3.Endpoints object at 0x1091136d0>, 
'primary_location': 'ukwest', 
'status_of_primary': <AccountStatus.available: 'available'>, 
'last_geo_failover_time': None, 
'secondary_location': None, 
'status_of_secondary': None, 
'creation_time': datetime.datetime(2020, 6, 16, 12, 49, 15, 727609, tzinfo=<isodate.tzinfo.Utc object at 0x1074edad0>), 
'custom_domain': None, 
'secondary_endpoints': None, 
'encryption': <azure.mgmt.storage.v2018_02_01.models.encryption_py3.Encryption object at 0x109113650>, 
'access_tier': <AccessTier.hot: 'Hot'>, 
'enable_https_traffic_only': True, 
'network_rule_set': <azure.mgmt.storage.v2018_02_01.models.network_rule_set_py3.NetworkRuleSet object at 0x109113850>, 
'is_hns_enabled': None
}

Storage account <REDACTED> changed to standard_grs SKU

{
'additional_properties': {}, 
'id':'/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Storage/storageAccounts/<REDACTED>', 
'name': '<REDACTED>', 
'type': 'Microsoft.Storage/storageAccounts', 
'tags': {}, 
'location': 'ukwest', 
'sku': <azure.mgmt.storage.v2018_02_01.models.sku_py3.Sku object at 0x109104a90>, 
'kind': <Kind.storage_v2: 'StorageV2'>, 
'identity': None, 
'provisioning_state': <ProvisioningState.succeeded: 'Succeeded'>, 
'primary_endpoints': <azure.mgmt.storage.v2018_02_01.models.endpoints_py3.Endpoints object at 0x109104c90>, 
'primary_location': 'ukwest', 
'status_of_primary': <AccountStatus.available: 'available'>, 
'last_geo_failover_time': None, 'secondary_location': 'uksouth', 'status_of_secondary': <AccountStatus.available: 'available'>, 
'creation_time': datetime.datetime(2020, 6, 16, 12, 49, 15, 727609, tzinfo=<isodate.tzinfo.Utc object at 0x1074edad0>), 
'custom_domain': None, 
'secondary_endpoints': None, 
'encryption': <azure.mgmt.storage.v2018_02_01.models.encryption_py3.Encryption object at 0x109104950>, 
'access_tier': <AccessTier.hot: 'Hot'>, 
'enable_https_traffic_only': False, 
'network_rule_set': <azure.mgmt.storage.v2018_02_01.models.network_rule_set_py3.NetworkRuleSet object at 0x109104a50>, 
'is_hns_enabled': None
}
```

I have not yet got round to running your script, but will do so and let you know the output
