### ISSUE TITLE
Ansible 2.10 and azure

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-sdk-for-python#14386]
**Describe the bug**
Unable to use ansible azure modules in Ansible 2.10. 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansible-test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**To Reproduce**
```
pip3 install ansible
pip3 install azure-cli
```
also tried
```
pip3 install azure-requirements.txt
```
and
```
pip3 install azure==4.0.0
```

***Code Snippet***
```
- hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
  - name: "get virtual machine facts by tag {{ tag }}"
    azure_rm_virtualmachine_info:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      tags:
        - type:{{ tag }}
    register: virtualmachine_facts
    delegate_to: localhost
```

**Setup (please complete the following information):**
 - Python Version: Python 3.8.5

```
ansible 2.10.2
  config file = /home/nbm/Ansible/ansible-dce/ansible.cfg
  configured module search path = ['/home/nbm/Ansible/ansible-dce/Modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added
