### ISSUE TITLE
Add BeforeTestSteps/AfterTestSteps to `archetype-sdk-client` 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#19172]
An example invocation to support a new feature that @iscai-msft  is working on for azure-core should look like this.

```yml
extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: core
    Artifacts:
    - name: azure-core
      safeName: azurecore
    - name: azure-mgmt-core
      safeName: azuremgmtcore
    - name: azure-core-tracing-opencensus
      safeName: azurecorecoretracingopencensus
    - name: azure-core-tracing-opentelemetry
      safeName: azurecorecoretracingtelemetry
    - name: azure-common
      safeName: azurecommon
    BeforeTestSteps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'scripts/devops_tasks/start_coretestserver.py'
            print('##vso[task.setvariable variable=FLASK_PID]<CHECKCALLRESULT>')
        displayName: "Start CoreTestServer"

    AfterTestSteps:
      - pwsh:
          kill $(FLASK_PID)
        displayName: "Shut Down CoreTestServer"
        
```
