### ISSUE TITLE
AzureML DateTime values are changed when read as parquet

### ISSUE THREAD

**Issue by muhammad-s-zainal** [Azure/azure-sdk-for-python#19277]
- **Package Name & Version**:  
azureml-core==1.30.0
azureml-dataset-runtime==1.30.0
- **Operating System**: Windows
- **Python Version**: 3.7.4

**Describe the bug**
Datetime values are changed when importing data from Azure Blob to Azure ML datasets.

**To Reproduce**
1. Create a pandas dataframe with a column of datetime strings and parse them accordingly
```
d = {"Date": ["2020-03-06", "2021-01-05", "2016-01-30", "2019-12-14"]}
df = pd.DataFrame(data=d)
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d")
```
![image](https://user-images.githubusercontent.com/43106089/122145977-c7ecef80-ce88-11eb-85ff-6933e4fbd6c2.png)

2. Save this dataframe as a .parquet
3. Upload to Azure Blob
4. Create a Tabular Dataset object with the uploaded file
```
datastore = workspace.get_default_datastore()
datastore_path = [(datastore, "filename.parquet")]
azureml_df = Dataset.Tabular.from_parquet_files(path=datastore_path)
```
5. Print the dataframe
![image](https://user-images.githubusercontent.com/43106089/122145911-b0156b80-ce88-11eb-9b8d-44af043faa85.png)

**Expected behavior**
The datetime values should not have changed.

**Additional context**
To investigate further, we can cast the datetime to int:
![image](https://user-images.githubusercontent.com/43106089/122146037-dfc47380-ce88-11eb-8d78-d0b5d20c98a1.png)
which gives us a 15 digit number.

We also cast the original df to int:
![image](https://user-images.githubusercontent.com/43106089/122146057-e9e67200-ce88-11eb-84ea-17fef99661c0.png)
which instead gives us an 18 digit number.

Three trailing zeroes have been stripped. A simple workaround would be to multiply this column by 1000 then convert it back to datetime again but I would like to know if there's something I'm missing in between reading the parquet from AzureML or if the problem is on Azure's side.

Also, I am using conda 4.10.1 to build my environment from the following environment.yml file:
```
 name: datetime_env
 channels:
   - defaults
 dependencies:
   - python=3.7
   - pandas=1.2.2
   - notebook==6.4.0
   - pip=21.1.1
   - pip:
       - azureml-core==1.30.0
       - azureml-dataset-runtime==1.30.0
       - catboost==0.26
```
