### ISSUE TITLE
`final-state-via` introduced inconsistent behavior for long running operations

### ISSUE THREAD

**Issue by necusjz** [Azure/azure-sdk-for-python#24451]
- **Package Name**: azure-core
- **Package Version**: 1.24.0 
- **Operating System**: Windows
- **Python Version**: 3.8.10

**Describe the bug**
The following PR introduces support for "final-state-via":
- https://github.com/Azure/azure-sdk-for-python/pull/22713

But, this document says "Azure-AsyncOperation" has higher priority:
- https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations#url-to-monitor-status

Is there an inconsistency when we have both "Azure-AsyncOperation" and "Location" (with final-state-via) is the header?

**To Reproduce**
E.g., we have a header like this:
```
headers:
  ...
  azure-asyncoperation:
  - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/westcentralus/operations/ca9109a1-acc0-499d-8c9f-9fb75e72050d?api-version=2021-08-01
  ...
  location:
  - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/westcentralus/operationResults/ca9109a1-acc0-499d-8c9f-9fb75e72050d?api-version=2021-08-01
```

azure-core==1.21.1 will always go through "azure-asyncoperation", but azure-core==1.24.0 will go through "location", like:
- https://github.com/Azure/azure-cli-extensions/pull/4811

**Expected behavior**
Version upgrades keep consistent behavior for long running operations.

**Screenshots**

**Additional context**
