### ISSUE TITLE
Add precommit hooks to repo

### ISSUE THREAD

**Issue by needuv** [Azure/azure-sdk-for-python#26509]
**Is your feature request related to a problem? Please describe.**

We would like to have pre-commit hooks in azure-sdk-for-python that can automate fixing common linting issues. These hooks can be things such as removing trailing whitespaces for lines, making sure files have an extra line at the end of the file, running `black` to format code, running `pycln` to clean up unused imports, running `isort` to sort imports, and many other things.

**Describe the solution you'd like**

The ML SDK team was using a precommit configuration that looked like this: 

```yaml

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (^docs/)|(^tests/test_configs/)|(^autorest/)|(^src/cli/src/machinelearningservices/(README.md|setup.py|azext_mlv2/manual/__init__.py))|(^src/azure-ai-ml/azure/ai/ml/_restclient/)|(^src/azure-ai-ml/azure/ai/ml/_vendor/)

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            exclude: src/azure-ai-ml/tests/test_configs/components/invalid
          # -   id: check-added-large-files
          - id: check-json
          - id: check-merge-conflict
    - repo: https://github.com/psf/black
      rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+
            args:
                - "--line-length=120"
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: flake8
    - repo: https://github.com/hadialqattan/pycln
      rev: v0.0.2 # Possible releases: https://github.com/hadialqattan/pycln/tags
      hooks:
          - id: pycln
            name: "Clean unused python imports"
            args: [--config=setup.cfg]
            exclude: src/azure-ai-ml/tests/test_configs
    - repo: https://github.com/pycqa/isort
      rev: 5.8.0
      hooks:
        - id: isort
          # stages: [commit]
          name: isort-python
          # Use black profile for isort to avoid conflicts
          # see https://github.com/PyCQA/isort/issues/1518
          args: ["--profile", "black", --line-length=120]

```

before migrating code to `azure-sdk-for-python`. We'd like to continue to use something that's similar or, preferably, the exact same as it has helped us maintain relatively clean and consistent-looking code. We could enable this initially just for the ML SDK if we don't want to risk adding it for the entire repo.

**Describe alternatives you've considered**

**Additional context**
pre-commit documentation: https://pre-commit.com/
