### ISSUE TITLE
Question: how to set blob metadata in AML pipeline

### ISSUE THREAD

**Issue by Howzaa** [Azure/azure-sdk-for-python#28080]
Input data is of type uri_folder. Here is the relevant YAML for the component

```
Inputs:
  datapath:
    type: uri_folder
    path: <datastore_url>
```
I can create a new blob from within the component using

```
with open(os.path.join(args.datapath, "content.txt"),"w") as f:
        f.write(content)
```
How to update the metadata of this blob? I am using AML v2, python SDK. Thank you!
