### ISSUE TITLE
Large file downloads hang indefinitely

### ISSUE THREAD

**Issue by YuvalItzchakov** [Azure/azure-sdk-for-python#28713]
- **Package Name**: 
azure-core                               1.25.1
azure-storage-blob                       12.8.1
azure-storage-common                     2.1.0
azure-storage-file                       2.1.0

- **Operating System**
  - Debian GNU/Linux 11 (bullseye)
  - MacOS Monterey 12.5.1

- **Python Version**: 
Python 3.7.13 (Server) / Python 3.8.13 (Local)

**Describe the bug**
While trying to download large files >= 17GB, the Python SDK and the Azure CLI respectively get stuck before finishing the download, usually around 99.(3/5)%. This is due to some of the chunks being downloaded hanging and never timing out / retrying.

While trying to download a file with the following parameters, using `BlobClient.download_blob`:

- max_concurrency = 20
- timeout = 1800

The chunks that are stuck, yield the following stack trace (this is from the live stuck process):

Locally: 

```
Thread 0x2A704F000 (idle): "ThreadPoolExecutor-0_6"
    read (ssl.py:1130)
        Arguments:
            self: <SSLSocket at 0x1057e5c00>
            len: 8192
            buffer: <memoryview at 0x1043ea740>
    recv_into (ssl.py:1274)
        Arguments:
            self: <SSLSocket at 0x1057e5c00>
            buffer: <memoryview at 0x1043ea740>
            nbytes: 8192
            flags: 0
    readinto (socket.py:705)
        Arguments:
            self: <SocketIO at 0x105003c70>
            b: <memoryview at 0x1043ea740>
    read (http/client.py:465)
        Arguments:
            self: <HTTPResponse at 0x10501e080>
            amt: 4096
    read (urllib3/response.py:519)
        Arguments:
            self: <HTTPResponse at 0x1050001c0>
            amt: 4096
            decode_content: True
            cache_content: False
        Locals:
            flush_decoder: False
            fp_closed: False
    stream (urllib3/response.py:576)
        Arguments:
            self: <HTTPResponse at 0x1050001c0>
            amt: 4096
            decode_content: True
        Locals:
            data: <bytes at 0x106225600>
    generate (requests/models.py:758)
        Locals:
            chunk: <bytes at 0x106225600>
    next (azure/core/pipeline/transport/_requests_basic.py:169)
        Arguments:
            self: <StreamDownloadGenerator at 0x105002c20>
        Locals:
            internal_response: <Response at 0x105003e20>
    process_content (azure/multiapi/storagev2/blob/v2021_06_08/_download.py:52)
        Arguments:
            data: <StreamDownloadGenerator at 0x105002c20>
            start_offset: 0
            end_offset: 0
            encryption: {"required": False, "key": None, "resolver": None}
    _download_chunk (azure/multiapi/storagev2/blob/v2021_06_08/_download.py:217)
        Arguments:
            self: <_ChunkDownloader at 0x104406470>
            chunk_start: 2835349504
            chunk_end: 2839543807
        Locals:
            download_range: (2835349504, 2839543807)
            offset: (0, 0)
            range_header: "bytes=2835349504-2839543807"
            range_validation: None
            retry_active: True
            retry_total: 3
            _: "primary"
            response: <StreamDownloadGenerator at 0x105002c20>
```

Remote (server):

```
Thread 21134 (idle): "ThreadPoolExecutor-0_3"
    poll (/lib/x86_64-linux-gnu/libc-2.31.so)
    0x7f109531b01d (/usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so)
    0x7f109531f81f (/usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so)
    read (/usr/local/lib/python3.7/ssl.py:929)
        Arguments:
            self: <SSLSocket at 0x7f105c194f30>
            len: 8192
            buffer: <memoryview at 0x7f1063464ef0>
    recv_into (/usr/local/lib/python3.7/ssl.py:1071)
        Arguments:
            self: <SSLSocket at 0x7f105c194f30>
            buffer: <memoryview at 0x7f1063464ef0>
            nbytes: 8192
            flags: 0
    readinto (/usr/local/lib/python3.7/socket.py:589)
        Arguments:
            self: <SocketIO at 0x7f104c5c4490>
            b: <memoryview at 0x7f1063464ef0>
    readinto (/usr/local/lib/python3.7/http/client.py:509)
        Arguments:
            self: <HTTPResponse at 0x7f104c5c4250>
            b: <bytearray at 0x7f104c7b6df0>
    read (/usr/local/lib/python3.7/http/client.py:465)
        Arguments:
            self: <HTTPResponse at 0x7f104c5c4250>
            amt: 4096
        Locals:
            b: <bytearray at 0x7f104c7b6df0>
    read (/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py:518)
        Arguments:
            self: <HTTPResponse at 0x7f105c1ac310>
            amt: 4096
            decode_content: True
            cache_content: False
        Locals:
            flush_decoder: False
            fp_closed: False
    stream (/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py:575)
        Arguments:
            self: <HTTPResponse at 0x7f105c1ac310>
            amt: 4096
            decode_content: True
        Locals:
            data: <bytes at 0x7f1050130ae0>
    generate (/home/airflow/.local/lib/python3.7/site-packages/requests/models.py:816)
    __next__ (/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py:169)
        Arguments:
            self: <StreamDownloadGenerator at 0x7f104c7b6190>
        Locals:
            internal_response: <Response at 0x7f104c6be810>
    process_content (/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_download.py:52)
        Arguments:
            data: <StreamDownloadGenerator at 0x7f104c7b6190>
            start_offset: 0
            end_offset: 0
            encryption: {"required": False, "key": None, "resolver": None}
    _download_chunk (/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_download.py:211)
        Arguments:
            self: <_ChunkDownloader at 0x7f106937b5d0>
            chunk_start: 10670309376
            chunk_end: 10674503679
        Locals:
            download_range: (10670309376, 10674503679)
            offset: (0, 0)
            range_header: "bytes=10670309376-10674503679"
            range_validation: None
            retry_active: True
            retry_total: 3
            _: "primary"
            response: <StreamDownloadGenerator at 0x7f104c7b6190>
    process_chunk (/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_download.py:129)
        Arguments:
            self: <_ChunkDownloader at 0x7f106937b5d0>
            chunk_start: 10670309376
        Locals:
            chunk_end: 10674503680
```

And the following error message is printed out (this is from the Azure CLI):

> Alive[############################################################### ]  99.8149%
urllib3.connectionpool: Connection pool is full, discarding connection: x.blob.core.windows.net
Alive[############################################################### ]  99.8380%
urllib3.connectionpool: Connection pool is full, discarding connection: x.blob.core.windows.net
Alive[############################################################### ]  99.8612%
urllib3.connectionpool: Connection pool is full, discarding connection: x.blob.core.windows.net
Alive[############################################################### ]  99.8843%
urllib3.connectionpool: Connection pool is full, discarding connection: x.blob.core.windows.net
Alive[############################################################### ]  99.9074%
urllib3.connectionpool: Connection pool is full, discarding connection: x.blob.core.windows.net
Alive[############################################################### ]  99.9306%

Using the Azure CLI this reproduces every time when trying to fetch a large file. When using the Python SDK directly it will sometimes fail and sometimes succeed.

**To Reproduce**
Steps to reproduce the behavior (Azure CLI):
1. Create a large file, >= 17 GB
4. Store it in blob storage
5. Install Azure CLI
6. Attempt to download the file using `az storage blob download` passing the above parameters to the command

Steps to reproduce the behavior (Python SDK directly):
1. Create a large file, >= 17 GB
2. Store it in blob storage
3. Create a new Python project, install Azure Python SDK
4. Run the following code:

```
    from azure.storage.blob import BlobServiceClient
    from time import time
    import logging

    conn_id = <your_con_id>
    client = BlobServiceClient.from_connection_string(conn_id)

    blob_client = client.get_blob_client(container=<container_name>,
                                         blob='<blob>')

    print(f'Fetching blob from storage, {time()}')
    res = blob_client.download_blob(max_concurrency=20, timeout=1800)
    print(f'Starting to read file, {time()}')
    data = res.readall()
```
**Expected behavior**

Either the chunk that is hanging should fail on timeout and retry, or if it exhausted all retries it should fail the download. Otherwise, the download should complete.

**Additional Context**

Related bugs: 
- https://github.com/Azure/azure-sdk-for-python/issues/10572
- https://github.com/Azure/azure-sdk-for-python/issues/25358
- https://stackoverflow.com/questions/72232934/azure-blob-python-library-hanging-on-readinto-function
