### ISSUE TITLE
Package activity status should come from pyproject.toml not setup classifiers

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#29703]
Within CI, we do not build packages or test packages that have been marked as `inactive` in their classifiers.

This is handled by a [single location](https://github.com/Azure/azure-sdk-for-python/blob/a826f67f72ddac12bff7c026fe64a37c941f9ba5/tools/azure-sdk-tools/ci_tools/functions.py#L207) in code.

We need to update this to instead honor a new variable in the pyproject toml section (this example is from azure-core):

```toml
[tool.azure-sdk-build]
mypy = true
type_check_samples = false
verifytypes = true
pyright = false
build = false # <-- the new variable, indicating that this package should not be built or tested
```

Then, within `is_package_inactive()`, we want examine the value of this new variable by utilizing the function [`is_check_enabled(package_path, 'build', False)`.](https://github.com/Azure/azure-sdk-for-python/blob/a826f67f72ddac12bff7c026fe64a37c941f9ba5/tools/azure-sdk-tools/ci_tools/environment_exclusions.py#L37)

Note that the 3rd argument to `is_check_enabled` is the default bool that will be returned. Ensure that we only skip build/test of a package if build = false. All other options (including `build=true`) should be treated as

> this package is active.
