### ISSUE TITLE
AzureML On Behalf of (OBO) with AzureMLOnBehalfOfCredential does not work for a pipeline

### ISSUE THREAD

**Issue by o-fedorov** [Azure/azure-sdk-for-python#30104]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.5.0
- **Operating System**: MacOS
- **Python Version**: 3.10.7

**Describe the bug**
I am struggling trying to make «AzureML On Behalf of (OBO)» feature work for a pipeline job. I am following this example: <https://github.com/Azure/azureml-examples/tree/main/cli/jobs/single-step/on-behalf-of>, which works as long as I submit a single `command` job. When I try to scale it to a pipeline, it stops working. Namely:
1. The logs contain following records:
_AzureMLOnBehalfOfCredential.get_token failed: No token received.
…
azure.core.exceptions.ClientAuthenticationError: No token received.
2. I see that now the code uses http://127.0.0.1:46808/MSI/auth to request a token, while the successfully executed job used `http://localhost:46809/OBO/token`

**To Reproduce**
1. Create a component like the following. For this example, its path is `components/obo/test_obo.py`
```python
import logging
from pathlib import Path

import jwt
from azure.ai.ml.identity import AzureMLOnBehalfOfCredential


def test_obo():
    """Test On-Behalf-Of Credential."""
    # Display the URL used for auth
    logging.getLogger("urllib3.connectionpool").setLevel(logging.DEBUG)
    logging.basicConfig(level=logging.INFO)

    credential = AzureMLOnBehalfOfCredential()
    token = credential.get_token("https://ml.azure.com/.default")
    claims = jwt.decode(token.token, options={"verify_signature": False})
    print({k: claims[k] for k in ["aud", "oid", "appid"]})

if __name__ == "__main__":
    test_obo()
```

2. Create Conda environment for the component, in `components/obo/conda.yaml`
```yaml
name: test-obo-env-py310
channels:
  - conda-forge
dependencies:
  - python=3.10.7
  - pip=22.3.1

  - pip:
    - azure-ai-ml==1.5.0
    - pyjwt==2.6.0
```
3. Create a one-step pipeline, change `compute` if required. Note the `identity` section at the bottom.
```yaml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

jobs:
  test_obo:
    type: command
    code: components/obo
    command: python test_obo.py
    compute: azureml:cpu-cluster
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
      conda_file: components/obo/conda.yaml
    identity:
      type: user_identity
```

**Expected behavior**

- The pipeline is successfully executed.
- The logs show that `http://localhost:46809/OBO/token` is used to get a token.
- The printed out claims are similar to provided below, with `oid` equal to my Object ID in AAD.
```python
{'appid': '18a66f5f-dbdf-4c17-9dd7-1634712a9cbe',
 'aud': 'https://ml.azure.com',
 'oid': ...}
```

**Actual behavior**
The job fails with the following log entries:
```text
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'http://127.0.0.1:46808/MSI/auth?resource=REDACTED'
Request method: 'GET'
Request headers:
    'User-Agent': 'azure-ai-ml/1.5.0'
No body was attached to the request
DEBUG:urllib3.connectionpool:http://127.0.0.1:46808 "GET /MSI/auth?resource=https://ml.azure.com HTTP/1.1" 403 0
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 403
Response headers:
    'Date': 'Thu, 27 Apr 2023 10:42:46 GMT'
    'Content-Length': '0'
_AzureMLOnBehalfOfCredential.get_token failed: No token received.
```
