### ISSUE TITLE
AML SDKv2 - invoke operation on batch endpoint produces errors and creates more than one job

### ISSUE THREAD

**Issue by Sysa** [Azure/azure-sdk-for-python#31166]
- **Package Name**: AML SDK v2 ( azure-ai-ml )
- **Package Version**: azure-ai-ml 1.8.0
- **Operating System**: Ubuntu 20.04.5 LTS (Focal Fossa)
- **Python Version**: 3.8.16

**Describe the bug**
Hello there, I'm trying to move a pipeline from SDK v1 to SDK v2 (yaml based) and there is weird behaviour of `ml_client.batch_endpoints.invoke()` - [link to the method](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.operations.batchendpointoperations?view=azure-python#azure-ai-ml-operations-batchendpointoperations-invoke)
In short: after calling .invoke() - it returns REST API error but also submits about ~50 jobs at the same minute. See more assumptions about it in additional section below.

Also, more code examples below.

**To Reproduce**
Steps to reproduce the behaviour:
1. You should have a valid authenticated ml_client object as prerequisite.
2. Load component from YAML file
3. Create a batch endpoint
4. Create a deployment for the batch endpoint from previous step .3
5. Update batch from step .3 with deployment from step .4 and set it as default.
6. Submit a job by invoking batch endpoint from step .3
7. Wait for response with an exception
8. Check jobs, it should have multiple jobs submitted for last ~minute.

**Expected behaviour**
I expect a call of `.invoke()` function on a batch endpoint will return one (1) batch job only and not a pack of it with errors.

**Screenshots**
How it looks from AML UI (jobs were cancelled manually to not waste compute resource):

<img width="857" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/5188118/afdc374a-c9fd-4624-845a-83883a7016f1">

**Additional context**
The number of submitted jobs differs each time, it is either 49 or 48 for example. After invoking the batch endpoint it feels like an attempt to submit an actual job but it does not get any response back so it tries to submit it as hard as it can until it gets blocked by the API endpoint and hence returns 500 error. Invoke request was sent from AML compute instance in the same workspace, using VS Code.
The only big difference from working simpler examples from microsoft repos/docs I can notice - is in pipeline_endpoint.yaml for second component step i'm using in input one output from previous component step: `model: ${{parent.jobs.cf_train.outputs.model_output}}` - but it does not feels like a problem and should be fine I guess?

**RETURNED RESPONSE ERROR TEXT**

```
Exception has occurred: HttpResponseError
* 
Received 500 from a service request
Content: {
  "error": {
    "code": "ServiceError",
    "severity": null,
    "message": "Received 500 from a service request",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": "POST https://batch-endpoint.vienna-westeurope.svc/batch-endpoint/v1.0/subscriptions/<HIDDEN SUBSCRIPTION ID>/resourceGroups/<HIDDEN RG>/providers/Microsoft.MachineLearningServices/workspaces/<HIDDEN WS>/batchEndpoints/hidden-endpoint-name/deployments/hidden-deployment-name/jobs/",
    "details": [
      {
        "code": "InternalServerError",
        "severity": null,
        "message": "{\n  \"error\": {\n    \"code\": \"ServiceError\",\n    \"severity\": null,\n    \"message\": \"InternalServerError\",\n    \"messageFormat\": null,\n    \"messageParameters\": null,\n    \"referenceCode\": null,\n    \"detailsUri\": null,\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": null,\n    \"additionalInfo\": null\n  },\n  \"correlation\": {\n    \"operation\": \"hidden-operation-id\",\n    \"request\": \"b1e0a2cd984fc6ca\"\n  },\n  \"environment\": \"westeurope\",\n  \"location\": \"westeurope\",\n  \"time\": \"2023-07-17T09:53:45.0859255+00:00\",\n  \"componentName\": \"batch-endpoint\"\n}",
        "messageFormat": null,
        "messageParameters": {},
        "referenceCode": null,
        "detailsUri": null,
        "target": null,
        "details": [],
        "innerError": null,
        "debugInfo": null,
        "additionalInfo": null
      }
    ],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "hidden-operation-id",
    "request": "hidden-request-id"
  },
  "environment": "westeurope",
  "location": "westeurope",
  "time": "2023-07-17T09:53:45.0902512+00:00",
  "componentName": "managementfrontend"
}
  File "/home/azureuser/cloudfiles/code/Users/hidden-user-id/projects/hidden-folder-id/aml/pipelines/hidden-folder-yaml/cf_construct_pipeline.py", line 182, in <module>
    job = ml_client.batch_endpoints.invoke(
azure.core.exceptions.HttpResponseError: Received 500 from a service request
Content: {
  "error": {
    "code": "ServiceError",
    "severity": null,
    "message": "Received 500 from a service request",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": "POST https://batch-endpoint.vienna-westeurope.svc/batch-endpoint/v1.0/subscriptions/<HIDDEN SUBSCRIPTION ID>/resourceGroups/<HIDDEN RG>/providers/Microsoft.MachineLearningServices/workspaces/<HIDDEN WS>/batchEndpoints/hidden-endpoint-name/deployments/hidden-deployment-name/jobs/",
    "details": [
      {
        "code": "InternalServerError",
        "severity": null,
        "message": "{\n  \"error\": {\n    \"code\": \"ServiceError\",\n    \"severity\": null,\n    \"message\": \"InternalServerError\",\n    \"messageFormat\": null,\n    \"messageParameters\": null,\n    \"referenceCode\": null,\n    \"detailsUri\": null,\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": null,\n    \"additionalInfo\": null\n  },\n  \"correlation\": {\n    \"operation\": \"hidden-operation-id\",\n    \"request\": \"b1e0a2cd984fc6ca\"\n  },\n  \"environment\": \"westeurope\",\n  \"location\": \"westeurope\",\n  \"time\": \"2023-07-17T09:53:45.0859255+00:00\",\n  \"componentName\": \"batch-endpoint\"\n}",
        "messageFormat": null,
        "messageParameters": {},
        "referenceCode": null,
        "detailsUri": null,
        "target": null,
        "details": [],
        "innerError": null,
        "debugInfo": null,
        "additionalInfo": null
      }
    ],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "hidden-operation-id",
    "request": "hidden-request-id"
  },
  "environment": "westeurope",
  "location": "westeurope",
  "time": "2023-07-17T09:53:45.0902512+00:00",
  "componentName": "managementfrontend"
}
```

**List of virtual env dependency packages**
```
Package                                Version
-------------------------------------- ------------
absl-py                                1.4.0
adal                                   1.2.7
anyio                                  3.6.2
appdirs                                1.4.4
applicationinsights                    0.11.10
argcomplete                            2.1.2
asosamlcore                            0.1.21
astunparse                             1.6.3
async-timeout                          4.0.2
attrs                                  23.1.0
azure-ai-ml                            1.8.0
azure-common                           1.1.28
azure-core                             1.26.4
azure-core-tracing-opentelemetry       1.0.0b9
azure-graphrbac                        0.61.1
azure-identity                         1.13.0
azure-mgmt-authorization               2.0.0
azure-mgmt-containerregistry           10.1.0
azure-mgmt-core                        1.4.0
azure-mgmt-keyvault                    10.2.1
azure-mgmt-monitor                     6.0.1
azure-mgmt-resource                    21.2.1
azure-mgmt-storage                     20.0.0
azure-monitor-opentelemetry            1.0.0b10
azure-monitor-opentelemetry-exporter   1.0.0b12
azure-storage-blob                     12.12.0
azure-storage-file-datalake            12.7.0
azure-storage-file-share               12.8.0
azureml-automl-core                    1.46.1.post1
azureml-core                           1.46.0
azureml-dataprep                       4.5.7
azureml-dataprep-native                38.0.0
azureml-dataprep-rslex                 2.11.4
azureml-dataset-runtime                1.46.0
azureml-mlflow                         1.49.0
azureml-pipeline                       1.46.0
azureml-pipeline-core                  1.46.0
azureml-pipeline-steps                 1.46.0
azureml-telemetry                      1.46.0
azureml-train-automl-client            1.46.0
azureml-train-core                     1.46.0
azureml-train-restclients-hyperdrive   1.46.0
backports.tempfile                     1.0
backports.weakref                      1.0.post1
bcrypt                                 4.0.1
black                                  22.12.0
bowler                                 0.9.0
CacheControl                           0.12.11
cachetools                             5.3.0
certifi                                2023.5.7
cffi                                   1.15.1
charset-normalizer                     3.1.0
click                                  8.1.3
cloudpickle                            2.2.1
colorama                               0.4.4
contextlib2                            21.6.0
cryptography                           37.0.4
cslug                                  0.7.0
dask                                   2022.1.1
databricks-cli                         0.17.7
deltalake                              0.10.0
Deprecated                             1.2.13
dill                                   0.3.6
distlib                                0.3.6
distro                                 1.8.0
docker                                 5.0.3
dotnetcore2                            3.1.23
entrypoints                            0.4
exceptiongroup                         1.1.1
fastapi                                0.95.1
fastavro                               1.7.4
feast                                  0.26.0
fissix                                 21.11.13
fixedint                               0.1.6
flatbuffers                            23.5.8
fsspec                                 2023.5.0
gast                                   0.4.0
gitdb                                  4.0.10
GitPython                              3.1.31
google-api-core                        2.11.0
google-auth                            2.17.3
google-auth-oauthlib                   1.0.0
google-pasta                           0.2.0
googleapis-common-protos               1.59.0
greenlet                               2.0.2
grpcio                                 1.54.0
grpcio-reflection                      1.48.2
h11                                    0.14.0
h5py                                   3.8.0
hiredis                                2.2.3
hirola                                 0.3.0
httpcore                               0.17.0
httptools                              0.5.0
httpx                                  0.24.0
humanfriendly                          10.0
idna                                   3.4
importlib-metadata                     4.13.0
importlib-resources                    5.12.0
iniconfig                              2.0.0
install                                1.3.5
isodate                                0.6.1
jaraco.classes                         3.2.3
jax                                    0.4.13
jeepney                                0.8.0
Jinja2                                 3.1.2
jmespath                               1.0.1
joblib                                 1.3.1
jsonpickle                             2.2.0
jsonschema                             4.17.3
keras                                  2.12.0
Keras-Preprocessing                    1.1.2
knack                                  0.9.0
libclang                               16.0.0
locket                                 1.0.0
lockfile                               0.12.2
Markdown                               3.4.3
MarkupSafe                             2.1.2
marshmallow                            3.19.0
microdict                              0.1.1
ml-dtypes                              0.2.0
mlflow-skinny                          1.28.0
mmh3                                   3.1.0
moreorless                             0.4.0
msal                                   1.22.0
msal-extensions                        0.3.1
msgpack                                1.0.4
msrest                                 0.7.1
msrestazure                            0.6.4
mypy                                   1.2.0
mypy-extensions                        1.0.0
ndg-httpsclient                        0.5.1
numpy                                  1.23.5
oauthlib                               3.2.2
opencensus                             0.11.2
opencensus-context                     0.1.3
opencensus-ext-azure                   1.1.9
opentelemetry-api                      1.15.0
opentelemetry-instrumentation          0.36b0
opentelemetry-instrumentation-dbapi    0.36b0
opentelemetry-instrumentation-django   0.36b0
opentelemetry-instrumentation-flask    0.36b0
opentelemetry-instrumentation-psycopg2 0.36b0
opentelemetry-instrumentation-redis    0.36b0
opentelemetry-instrumentation-requests 0.36b0
opentelemetry-instrumentation-wsgi     0.36b0
opentelemetry-sdk                      1.15.0
opentelemetry-semantic-conventions     0.36b0
opentelemetry-util-http                0.36b0
opt-einsum                             3.3.0
packaging                              21.3
pandas                                 1.5.3
pandavro                               1.5.2
paramiko                               2.12.0
partd                                  1.4.0
pathspec                               0.9.0
pip                                    23.1.2
pkginfo                                1.9.6
pkgutil_resolve_name                   1.3.10
platformdirs                           3.5.0
pluggy                                 1.0.0
portalocker                            2.7.0
proto-plus                             1.22.2
protobuf                               3.20.3
psutil                                 5.9.5
py-cpuinfo                             9.0.0
py4j                                   0.10.9.7
pyarrow                                8.0.0
pyasn1                                 0.5.0
pyasn1-modules                         0.3.0
pycparser                              2.21
pydantic                               1.10.7
pydash                                 4.9.0
Pygments                               2.15.1
PyJWT                                  2.7.0
pymssql                                2.2.7
PyNaCl                                 1.5.0
pyodbc                                 4.0.39
pyOpenSSL                              22.0.0
pyparsing                              3.0.9
pyrsistent                             0.19.3
PySocks                                1.7.1
pyspark                                3.4.0
pytest                                 7.4.0
pytest-benchmark                       4.0.0
pytest-mock                            3.11.1
python-dateutil                        2.8.2
python-dotenv                          1.0.0
pytz                                   2022.7.1
PyYAML                                 6.0
rapidfuzz                              2.13.7
redis                                  4.2.2
requests                               2.30.0
requests-oauthlib                      1.3.1
rsa                                    4.9
scikit-learn                           1.3.0
scipy                                  1.10.1
SecretStorage                          3.3.3
setuptools                             66.0.0
six                                    1.16.0
smmap                                  5.0.0
sniffio                                1.3.0
SQLAlchemy                             1.4.48
sqlalchemy2-stubs                      0.0.2a34
sqlparse                               0.4.4
starlette                              0.26.1
strictyaml                             1.6.1
tabulate                               0.9.0
tenacity                               8.2.2
tensorboard                            2.12.3
tensorboard-data-server                0.7.1
tensorboard-plugin-wit                 1.8.1
tensorflow                             2.12.0
tensorflow-estimator                   2.12.0
tensorflow-io-gcs-filesystem           0.32.0
termcolor                              2.3.0
threadpoolctl                          3.1.0
toml                                   0.10.2
tomli                                  2.0.1
toolz                                  0.12.0
tqdm                                   4.63.0
trove-classifiers                      2023.1.20
typeguard                              3.0.2
typing_extensions                      4.5.0
urllib3                                1.26.15
uvicorn                                0.22.0
uvloop                                 0.17.0
volatile                               2.1.0
watchfiles                             0.19.0
websocket-client                       1.5.1
websockets                             11.0.3
Werkzeug                               2.3.4
wheel                                  0.38.4
wrapt                                  1.14.1
zipp                                   3.15.0

```

**EXAMPLE CODE TO REPRODUCE**
main py script:
```
from azure.ai.ml import MLClient, Input, load_component
from azure.ai.ml.entities import (
    BatchEndpoint,
    PipelineComponentBatchDeployment,
)
from azure.identity import DefaultAzureCredential

interactions_date = "2023-06-18"
config_path = "aml/pipelines/collaborativefiltering/config/config.yaml"
compute_cluster = "nc6-v3"

ml_client = MLClient(DefaultAzureCredential(), **WORKSPACES["dev_yml"])

endpoint_name = "collaborative-filtering"
endpoint = BatchEndpoint(
    name=endpoint_name,
    description="collaborative-filtering",
)
ml_client.batch_endpoints.begin_create_or_update(endpoint).result()
endpoint = ml_client.batch_endpoints.get(name=endpoint_name)

pipeline_endpoint_component = load_component(
    source="aml/pipelines/collaborative_filtering_yaml/pipeline_endpoint.yml"
)

deployment = PipelineComponentBatchDeployment(
    name="cf-train-save",
    description="collaborative-filtering-train",
    endpoint_name=endpoint.name,
    component=pipeline_endpoint_component,
    settings={"continue_on_step_failure": False, "default_compute": compute_cluster},
)
ml_client.batch_deployments.begin_create_or_update(deployment).result()

# set default deployment for batch endpoint:
endpoint = ml_client.batch_endpoints.get(endpoint_name)
endpoint.defaults.deployment_name = deployment.name
ml_client.batch_endpoints.begin_create_or_update(endpoint).result()

# invoke
job = ml_client.batch_endpoints.invoke(
    endpoint_name=endpoint.name,
    inputs={
        "gender": Input(type="string", default="male"),
        "interactions_date": Input(type="string", default=interactions_date),
        "config_path": Input(type="string", default=config_path),
        "extra_args": None,
        "compute_emb_output_path": Input(
            type="uri_folder",
            path="azureml:///--hidden--/paths/features/",
        ),
    },
)
```

aml/pipelines/collaborative_filtering_yaml/pipeline_endpoint.yml:
```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

name: collaborative_filtering_pipeline
display_name: CF pipeline endpoint
description: Collaborative Filtering pipeline endpoint from yaml
inputs:
  gender:
    type: string
    default: male
  interactions_date:
    type: string
  config_path:
    type: string
    default: "pipelines/collaborativefiltering/config/config.yaml"
  extra_args:
    type: string
    optional: true
  compute_emb_output_path:
    type: uri_folder
jobs:
  cf_train:
    type: command
    component: ./cf_train.yml
    inputs:
      interactions_date: ${{parent.inputs.interactions_date}}
      config_path: ${{parent.inputs.config_path}}
      extra_args: ${{parent.inputs.extra_args}}
    outputs:
      model_output:
        type: uri_folder
  cf_save:
    type: command
    component: ./cf_save.yml
    inputs:
      output_path: ${{parent.inputs.compute_emb_output_path}}
      interactions_date: ${{parent.inputs.interactions_date}}
      model: ${{parent.jobs.cf_train.outputs.model_output}}
      extra_args: ${{parent.inputs.extra_args}}
```
./cf_train.yml:
```
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: collaborativefiltering_train
display_name: collaborativefiltering_train
description: collaborativefiltering_train
version: 0.0.1
inputs:
  interactions_date:
    type: string
    # format: date-time
  config_path:
    type: string
    default: "pipelines/collaborativefiltering/config/config.yaml"
  extra_args:
    type: string
    optional: true
outputs:
  model_output:
    type: uri_folder
# code: "../../../aml/"
code: "../../../"
command: python aml/steps/collaborativefiltering_train/script.py --interactions-date ${{inputs.interactions_date}} --config ${{inputs.config_path}} $[[--extra_args ${{inputs.extra_args}}]] aml/pipelines/collaborativefiltering/config/cf_owl_male.yaml
environment: azureml:poc-dependencies-only-gpu@latest
```

./cf_save.yml
```
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: compute_item_embeddings_and_save
display_name: compute_item_embeddings_and_save
description: compute_item_embeddings_and_save
version: 0.0.1
inputs:
  output_path:
    type: uri_folder
  interactions_date:
    type: string
  model:
    type: uri_folder
  extra_args:
    type: string
    optional: true
outputs:
  model_output:
    type: uri_folder
code: "../../../"
command: python aml/steps/compute_item_embeddings_and_save/step.py --output_path ${{inputs.output_path}} --interactions-date ${{inputs.interactions_date}} --model ${{inputs.model}} $[[--extra_args ${{inputs.extra_args}}]] aml/pipelines/collaborativefiltering/config/cf_owl_male.yaml
environment: azureml:poc-dependencies-only-gpu@latest
```
