### ISSUE TITLE
Bug in validation BatchDeploymentSchema

### ISSUE THREAD

**Issue by asos-rickbruins** [Azure/azure-sdk-for-python#33044]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.11.1
- **Operating System**: Linux 23.10.09
- **Python Version**: 3.8.10

**Describe the bug**
Validation error for BatchDeploymentSchema when using the field "settings". However, it is listed as a valid key in the yaml schema, [see documentation](https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-deployment-batch?view=azureml-api-2#yaml-syntax)

**To Reproduce**

**deployment.yaml**
```yaml 
$schema: https://azuremlschemasprod.azureedge.net/latest/batchDeployment.schema.json
name: collaborative-filtering-train
description: Train CF model and save embeddings
endpoint_name: collaborative-filtering-train
type: pipeline
component: ./pipeline.yaml
settings:
  continue_on_step_failure: false
  force_rerun: true

```

```python
from azure.ai.ml import load_batch_deployment

deployment = load_batch_deployment("deployment.yaml")

```
Error
```bash
marshmallow.exceptions.ValidationError: {'settings': ['Unknown field.']}
```

**Expected behavior**
No error, because the key is valid.

**Screenshots**

**Additional context**
