### ISSUE TITLE
Use DefaultAzureCredential() with service principal and federated identity credentials

### ISSUE THREAD

**Issue by ZhiliangWu** [Azure/azure-sdk-for-python#33332]
- **Package Name**: 
azure-identity
- **Package Version**: 
1.15.0
- **Operating System**:
Docker containers running [`mcr.microsoft.com/azure-cli@sha256:9564efe475cd9de3cce1d22e13674066d331fcd37a406e1f5140ff66dd2af13b`](https://mcr.microsoft.com/en-us/product/azure-cli/tags)
- **Python Version**: 
3.11.6

**Describe the bug**
I use service principal authentication to communicate with azure services. According to this [page](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?view=azureml-api-2&tabs=sdk#use-service-principal-authentication), I can set up environment variables to realize that. Meanwhile, as I run these jobs in Gitlab CI jobs, where they support [OpenID Connect to retrieve temporary credentials](https://docs.gitlab.com/ee/ci/cloud_services/azure/#retrieve-a-temporary-credential), I think this should also work. In CI jobs, it logs in successfully by running 

```
 az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
```
but when running
 
```python
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()
credential.get_token('https://management.azure.com/.default')
```
I got 

```console
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/html"
```

**To Reproduce**
1. Follow https://docs.gitlab.com/ee/ci/cloud_services/azure/#create-azure-ad-application-and-service-principal to configure OpenID Connect for respective repo 
2. Create `.gitlab-ci.yml` file as 

```yml
default:
  image: mcr.microsoft.com/azure-cli:latest

variables:
  AZURE_CLIENT_ID: "<client-id>"
  AZURE_TENANT_ID: "<tenant-id>"

auth:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
    - az account show
    - pip install azure-identity azure-ai-ml
    - python -c "from azure.identity import DefaultAzureCredential; credential = DefaultAzureCredential(); credential.get_token('https://management.azure.com/.default')"
```

**Expected behavior**
It should behave the same as setting environment variables of the service principal as described [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?view=azureml-api-2&tabs=sdk#use-service-principal-authentication).
