### ISSUE TITLE
Azure.Identity fails when using OIDC auth

### ISSUE THREAD

**Issue by gleb-boushev-effem** [Azure/azure-sdk-for-python#33801]
- **Package Name**:  azure.identity
- **Package Version**:  1.15.0
- **Operating System**: ubuntu 22.04
- **Python Version**:  3.10

**Describe the bug**
DefaultCredentials and AzureCliCredential fail to work properly in a Github Action that is using OIDC auth

**To Reproduce**
1. Follow the docs to create a GH repo with OIDC auth
2. create a long running python code that is using either DefaultCredentials or AzureCliCredential 

**Expected behavior**
Python SDK is able to obtain oAuth token to Azure

**Screenshots**

**Additional context**
Repro:

```
name: repro

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: xxx
  ARM_SUBSCRIPTION_ID: yyy
  ARM_TENANT_ID: zzz
  ARM_USE_OIDC: true

permissions:
  contents: read
  id-token: write

jobs:
  resourceGroup:
    runs-on:
    - azure-cli
    environment: development
    steps:
    - name: az login
      uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - run: |
        sudo apt-get update > /dev/null
        sudo -E apt-get install -y python3-dev python3.10-venv
      name: python setup
    - run: python3 -c "from time import sleep; sleep(600)"
      name: python sleep
    - run: |
        python3 -m venv ${{ github.workspace }}/venv
        source ${{ github.workspace }}/venv/bin/activate
        pip3 install azure-identity
        python -c "from azure.identity import AzureCliCredential
        print(AzureCliCredential().get_token('https://management.azure.com/').token)"
      name: python repro
```
