### ISSUE TITLE
Unable to control what is being logged and sent to App-insights by Azure Monitor log exporter.

### ISSUE THREAD

**Issue by summahto** [Azure/azure-sdk-for-python#34830]
I am using a Fast API app which is being started as module along with my API. There is also an Logging-config.yml file where we define what all loggers we have and what kind of handler is being used :

```yml
version: 1
disable_existing_loggers: false
loggers:
  root:
    level: WARNING  # WARNING is the default level
    handlers:
      - console
  uvicorn:
    qualname: uvicorn
    propagate: 0
    level: DEBUG
    handlers:
      - console
  my_api:
    qualname: my_api
    propagate: 0
    level: DEBUG
    handlers:
      - console

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stderr

formatters:
  standard:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  otel:
    format: '%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s trace_sampled=%(otelTraceSampled)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
```
    
    
    Now this is the code I am using to export logs from my application :

```py
configure_azure_monitor()
tracer = trace.get_tracer(__name__)

logger_provider = LoggerProvider()
set_logger_provider(logger_provider)

log_exporter = AzureMonitorLogExporter()
logger_provider.add_log_record_processor(BatchLogRecordProcessor(exporter=log_exporter))
handler = LoggingHandler()

logging.getLogger().addHandler(handler)
logging.getLogger().setLevel(logging.INFO)

logger = logging.getLogger(__name__) 

FastAPIInstrumentor.instrument_app(app)
```

I am passing the Application Insights connection string through my environment variables. Further this is how I start my FastAPI app with uvicorn. 
```bash
python -m uvicorn my_api.main:app
      --host 0.0.0.0
      --port 443
      --reload
      --log-config logging-dev.yml
```

As you can see, we have different logs for different modules and and if we fetch by __name__ you get the different logger. 

- What logger should be used to capture logs from all the modules and further be traced within a span under a tracer ?
- Currently, I did try with the root logger and I was able to send correlated logs to Application Insights, but there were duplicates of each log statements in App as well as instrumented libraries in App-Insights . Attaching the screenshot for the same. Why so ?

![image](https://github.com/Azure/azure-sdk-for-python/assets/20516618/7e7ff226-a44e-4185-9bff-0f1790ae715b)

- What should be the strategy to send the logs of all the modules specified in the startup command using the logging-config.yml ?
- How to provide Opentelemetry's loggingHandler in the logging-config.yml file ? Is configuring loggers through yml file supported?
