### ISSUE TITLE
OpenTelemetry SDK didn't send Resources

### ISSUE THREAD

**Issue by hcoona** [Azure/azure-sdk-for-python#36097]
- **Package Name**: `azure-monitor-opentelemetry`
- **Package Version**: 1.6.0
- **Operating System**: Windows 11
- **Python Version**: 3.12.4

**Describe the bug**

After instrumented my Flask app with `azure-monitor-opentelemetry`, I can find some logs and traces as expected. However, none of them carries my customized [resource](https://opentelemetry.io/docs/concepts/resources/). Even more, I cannot find any of the default resources from OpenTelemetry Python SDK. 

![image](https://github.com/Azure/azure-sdk-for-python/assets/712433/824a23b6-c9a7-4a23-9190-dd509aaabf40)

C# SDK can emit it correctly.

**To Reproduce**

1. Write any Flask app and instrument it with `azure-monitor-opentelemetry`.
2. Start it and do something to emit some logs to Azure Monitor.
3. Query with criteria `| where * contains 'opentelemetry'` (it's in default resource).

**Expected behavior**

Each of the logs, traces, requests, etc. should attach the resources.

**Comment by hcoona** [comment]
It's possible we need to also involve the exporter SDK owner to triage the issue.

**Comment by lzchen** [comment]
@hcoona 

How are you calling the apis? Are you passing in your custom `resource` into `configure_azure_monitor()` as shown in the [configuration settings](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry#usage)?

**Comment by hcoona** [comment]
Yes, and I challenge it because not only my customized resource but also OpenTelemetry SDK default resources were not properly transferred.

**Comment by lzchen** [comment]
@hcoona 

Could you paste a code snippet of how you are using the api?

**Comment by hcoona** [comment]
I'll try to provide a minimal workable sample in a few days.

**Comment by hcoona** [comment]
Reproduce steps:

1. Create Application Insights and Logs Analytics Workspace.
2. Assign yourself Monitoring Metrics Publisher role.
3. Paste my source code and execute it.

`main.py`:

```python
import logging
import time
from azure.identity import DefaultAzureCredential
from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry import trace
from opentelemetry.sdk.resources import Resource
from opentelemetry._logs import get_logger_provider

logging.basicConfig(format="%(asctime)s:%(levelname)s:%(message)s",
                    level=logging.INFO)

SERVICE_NAME = "OpenTelemetryAzureMonitorPythonMinimal"

credential = DefaultAzureCredential()
configure_azure_monitor(credential=credential,
                        resource=Resource.create({
                            "service.name":
                            SERVICE_NAME,
                            "my_custom_key":
                            "my_custom_value",
                        }))

logger = logging.getLogger(SERVICE_NAME)
tracer = trace.get_tracer(SERVICE_NAME)

if __name__ == "__main__":
    with tracer.start_as_current_span("main") as span:
        logging.info("Hello World!")
    time.sleep(15)
    get_logger_provider().shutdown()
```

`pyproject.toml`:

```toml
[project]
name = "OpenTelemetryAzureMonitorPythonMinimal"
version = "1.0.0-dev"
description = "Default template for PDM package"
authors = [
    {name = "Shuai Zhang", email = "shuaizhang@microsoft.com"},
]
dependencies = [
    "azure-monitor-opentelemetry>=1.6.0",
    "azure-identity>=1.16.1",
]
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[[tool.pdm.source]]
name = "pypi"
url = "https://pkgs.dev.azure.com/msazure/One/_packaging/One_PublicPackages/pypi/simple/"
verify_ssl = true
```

Execute (PowerShell):

```pwsh
az login
$env:APPLICATIONINSIGHTS_CONNECTION_STRING="<your-connection-string>"
pdm run main.py
```

Execute (Bash):

```bash
az login
APPLICATIONINSIGHTS_CONNECTION_STRING="<your-connection-string>" pdm run main.py
```

Check the logs in Application Insights -> Monitoring -> Logs.

```kql
union
    customEvents,
    dependencies,
    requests,
    traces
// | where message == "Hello World!"
| where * contains "d410ba5428176373"  // From any "Hello World" logs parent Id.
| take 50
```

Neither the log entry nor the dependency entry carries `my_custom_key`.
