### ISSUE TITLE
Azure Mgmt DNS does not handle throttling gracefully

### ISSUE THREAD

**Issue by elidhu** [Azure/azure-sdk-for-python#37002]
https://github.com/Azure/azure-sdk-for-python/blob/e4e8351eb9523bff0e6c4597478d04b9ceb9c14c/sdk/network/azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/_record_sets_operations.py#L1095C1-L1110C49

I believe the client should handle throttling by respecting the Retry-After header, it seems that this section of the code does not, there is no way to prevent this from raising an exception when being throttled, even the RetryPolicy settings don't seem to be respected.

Is there something we can do here?

**Comment by elidhu** [comment]
We do have a _lot_ of records in a single zone. From what I can gather [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#:~:text=2000%20per%20minute-,List%20By%20DNS%20Zone,-60%20per%20minute)

- 60 Requests per minute
- I can't find it officially, but I think 1000 records per page
- => 60000 records in any 1 minute (we have more that this)

We tried to implement a long backoff in a RetryPolicy, but this has no effect, I believe the codepath circumvents that

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Python SDK already has default [retry policy](https://github.com/Azure/azure-sdk-for-python/blob/fc5648dd682ad32e9ca9da6ee93ffc6b39ec748a/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L402). For further investigation, could you follow https://github.com/Azure/azure-sdk-for-python/wiki/Common-issues-about-Python-SDK#debug-guide to share the detailed logs?

**Comment by elidhu** [comment]
Hi, 

I am already using the RetryPolicy, and I don't believe it is taking effect. I suspect the code in the SDK is actually circumventing the RetryPolicy because it is accessing `self._client._pipeline`

For reference I am using the following RetryPolicy configuration:

```
    client_retry_policy:
      total_retries: 6
      # backoff_value = 2**(retry_number - 1) * backoff_factor => 20, 40, 80, 160, 320, 640
      backoff_factor: 20
      # min(backoff_max, backoff_value) => E.g min(640, 320) = 320 when retry_number = 5
      backoff_max: 640
```
