### ISSUE TITLE
Impossible to reuse an AzureML serveless spark jobs as components or inside a pipeline components. #azure-ai-ml

### ISSUE THREAD

**Issue by IsmaelGSerrano** [Azure/azure-sdk-for-python#37188]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.19
- **Operating System**: Windows 11
- **Python Version**:  3.9.15

**Describe the bug**
It is not possible to reuse a component in a pipeline when the component job is an AzureML serverless spark job.

**To Reproduce**

spark_job.yml:
```yml
$schema: https://azuremlschemasprod.azureedge.net/latest/sparkComponent.schema.json
name: imposible_spark_component
type: spark
description: "Spark job"
version: 1
inputs:
 data_name:
   type: string
outputs:
  output_path:
    type: uri_folder
    mode: direct
code: ./
entry:
  file: import_json_files.py
args: >-
  --data ${{inputs.data_name}}
  --output_path ${{outputs.output_path}}

conf:
  spark.driver.cores: 1
  spark.driver.memory: 2g
  spark.executor.cores: 2
  spark.executor.memory: 2g
  spark.executor.instances: 2
```

Python SDK pipeline creation
```python
from azure.ai.ml import load_component
from azure.ai.ml.dsl import pipeline

spark_load_data_component = load_component(
    source= r"pipeline\spark_job.yml")
spark_job = ml_client.components.create_or_update(spark_load_data_component)
spark_component = ml_client.components.get(spark_job.name)

@pipeline
def example_pipeline(
    input_name,
    output_path
):
    # Use registered pipeline function
    spark_load_data_step = spark_component(
        input_name=input_name
    )
    spark_load_data_step.outputs.output_path = Output(
        type="uri_folder", path=output_path)

    # Return: pipeline outputs
    return {
        "output_path": spark_load_data_step.outputs.output_path,
    }


pipeline_job = example_pipeline(
    input_name=input_name,
    output_path=f"azureml://datastores/workspaceblobstore/paths/raw_data"
)

pipeline_run = ml_client.jobs.create_or_update(
    pipeline_job,
    experiment_name='pipeline-with-spark-job-example'
)
```

**Error**
ValidationException                       Traceback (most recent call last)

MlException: {
  "result": "Failed",
  "errors": [
    {
      "message": "One of either compute or resources must be specified for Spark job",
      "path": "jobs.spark_load_data_step.resources",
      "value": null
    },
    {
      "message": "One of either compute or resources must be specified for Spark job",
      "path": "jobs.spark_load_data_step.compute",
      "value": null
    },
    {
      "message": "Compute not set",
      "path": "jobs.spark_load_data_step.compute",
      "value": null
    }
  ]
}

**Expected behavior**
I expect a pipeline with a single spark job step running in Azure ml.
If I create the pipeline defining the spark job not as a component, it works fine.
But the point here is that there is nothing written in the documentation that prevent the use of azureml spark serverless jobs as componets or component pipelines with serverless spark steps, which they also fail
