### ISSUE TITLE
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials'

### ISSUE THREAD

**Issue by aron89682** [Azure/azure-sdk-for-python#37790]
- **Package Name**: azure-identity
- **Package Version**: 1.18.0 and 1.19.0
- **Operating System**: linux-ubuntu
- **Python Version**: 3.10

**Describe the bug**
Locally all is good, however, when I run from a DevOps pipeline:
```
- task: AzureFunctionApp@2
    inputs:
      connectedServiceNameARM: "${{ parameters.azureSubscription }}"
      appType: "functionAppLinux"
      appName: ${{ parameters.functionAppName }}
      package: "$(System.DefaultWorkingDirectory)/**/*.zip"
      deploymentMethod: "zipDeploy"
```
      
It throws the error: ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials'.  My requirements file has azure-identity included in it.

**To Reproduce**
1. Have a python file with _from azure.identity import DefaultAzureCredential_
2. Have a requirements.txt file with _azure-identity_
3. Run pipeline with _- task: AzureFunctionApp@2_

**Expected behavior**
To be able to have my app service run from an Azure App Service as it does locally.

**Workaround**
azure-identity==1.17.1

**Comment by pvaneck** [comment]
This appears to be similar to the issue the [ML extension for Azure CLI was having](https://github.com/Azure/azure-sdk-for-python/issues/37491) where two sets of dependencies are combined, leading to incompatibilities.

I don't think there is anything we can do from the `azure-identity` SDK side. Normally, since `azure-identity >= 1.18.0` explicitly requires a version of `azure-core >= 1.31.0`, when `azure-identity` is installed, dependency resolution (e.g. via `pip`) ensures that all dependencies are compatible.

Something in the task might be pinning `azure-core` to a lower version, then that is being used with the newer version of `azure-identity` that's installed with your requirements, forgoing the dependency resolution.

What happens if you pin `azure-core==1.31.0` in your requirements.txt file? And are you able to deploy the Functions App from your local machine. If so, an issue with the maintainers of the AzureFunctionsApp will probably need to be raised.

**Comment by aron89682** [comment]
When pinning `azure-core==1.31.0`, I still received the error: `ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/agents/python/azure/core/credentials.py)`

When deploying directly from VS Code without pinning either azure-identity or azure-core, the same issue occurs.

I also have this in my pipeline:

```
  - task: UsePythonVersion@0
    displayName: "Use Python 3.10"
    inputs:
      versionSpec: 3.10

  - bash: |
      pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: "Install application dependencies"
```
The results of this are:

```
Installing collected packages: pytz, aniso8601, urllib3, typing-extensions, six, PyJWT, pycparser, portalocker, packaging, MarkupSafe, itsdangerous, isodate, idna, click, charset-normalizer, certifi, blinker, bcrypt, Werkzeug, requests, marshmallow, Jinja2, cffi, pynacl, flask, cryptography, azure-core, paramiko, flask-restful, azure-storage-blob, msal, msal-extensions, azure-identity
Successfully installed Jinja2-3.1.4 MarkupSafe-3.0.1 PyJWT-2.9.0 Werkzeug-3.0.4 aniso8601-9.0.1 azure-core-1.31.0 azure-identity-1.19.0 azure-storage-blob-12.23.1 bcrypt-4.2.0 blinker-1.8.2 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 click-8.1.7 cryptography-43.0.1 flask-3.0.3 flask-restful-0.3.10 idna-3.10 isodate-0.7.2 itsdangerous-2.2.0 marshmallow-3.22.0 msal-1.31.0 msal-extensions-1.2.0 packaging-24.1 paramiko-3.5.0 portalocker-2.10.1 pycparser-2.22 pynacl-1.5.0 pytz-2024.2 requests-2.32.3 six-1.16.0 typing-extensions-4.12.2 urllib3-2.2.3
```

If it helps at all, this is my full requirements.txt file:
```
flask
flask-restful
paramiko
marshmallow
azure-identity
azure-storage-blob
```
