### ISSUE TITLE
Network protected AzureML Workspace/Registry can be queried publicly via SDK

### ISSUE THREAD

**Issue by Mandur** [Azure/azure-sdk-for-python#40645]
Hello!

package used **azure.ai.ml 1.25.0**

We are currently working with a network-protected AzureML Registry and AML Workspace both only accessible via a private endpoint as described in the [documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-registry-network-isolation?view=azureml-api-2&tabs=existing) and [documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-workspace-vnet?view=azureml-api-2&tabs=required%2Cpe%2Ccli). 

Typically, when using network protection with other Azure resources (e.g. Storage) all access from public networks is denied.

However, we found out that with AzureML Registry, the SDK can be used to query information about environments, data, and components from the public internet. As the bulk of the data is hosted in other resource types (Azure blob storage and Azure Container Registry), we cannot __download all data__. However, this behavior is unaligned with other Azure resources and still exposes metadata (path on storage,...) and existence of the underlying data. 

Code examples below:

* When querying for specific environment:
``` python
client = MLClient(
        credential(),
        subscription_id=os.environ["SUBSCRIPTION_ID"],
        resource_group_name=os.environ["AML_REGISTRY_RESOURCE_GROUP_NAME"],
        registry_name=os.environ["AML_REGISTRY_NAME"],
    )
env = client.environments.get("identity", "719.8")
print(env)
```
Result:
```
Environment({'arm_type': 'environment_version', 'latest_version': None, 'image': None, 'intellectual_property': None, 'is_anonymous': False, 'auto_increment_version': False, 'auto_delete_setting': None, 'name': 'identity', 'description': None, 'tags': {}, 'properties': {'azureml.labels': ''}, 'print_as_yaml': False, 'id': 'azureml://registries/reg-sas-dev-ne/environments/identity/versions/719.8', 'Resource__source_path': '', 'base_path': '/workspaces/SandsPlatform', 'creation_context': <azure.ai.ml.entities._system_data.SystemData object at 0x7f817fcdd690>, 'serialize': <msrest.serialization.Serializer object at 0x7f817fd28b10>, 'version': '719.8', 'conda_file': None, 'build': <azure.ai.ml.entities._assets.environment.BuildContext object at 0x7f817fd0eb50>, 'inference_config': None, 'os_type': 'Linux', 'conda_file_path': None, 'path': None, 'datastore': None, 'upload_hash': None, 'translated_conda_file': None})
```

* Downloading a component:

``` python
env = client.components.download("identity", "7df286a")
print(env)
```

result:

```
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: identity
version: v_0.0.1
display_name: identity
description: Identity component for debugging the platform. The component propagates
  the unmodified input data to the output data.
type: command
inputs:
  input_data:
    type: uri_folder
    optional: false
outputs:
  output_data:
    type: uri_folder
command: python main.py --input '${{inputs.input_data}}' --output '${{outputs.output_data}}'
environment: azureml://registries/reg-s<...>/environments/identity/versions/v_0.0.1
code: azureml://registries/reg-s.../codes/b35f3bd8-f69d-4-d43357510113/versions/1
resources:
  instance_count: 1
is_deterministic: true

```

Is this behavior expected?
