### ISSUE TITLE
Failed to start job: PipelineRun contains duplicate PipelineRun output names, which is not allowed.

### ISSUE THREAD

**Issue by emepetres** [Azure/azure-sdk-for-python#40896]
I'm trying to start a batch job for a batch endpoint already deployed on AzureML. I'm getting the error `Failed to start job: PipelineRun contains duplicate PipelineRun output names, which is not allowed.` without more information. Any clue what could be happening? I'm out of ideas :)

The pipeline component that the deployment is trying to run is

```
# yaml-language-server: $schema=https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: nerfstudio_aas
display_name: Nerfstudio AAS Component
type: pipeline

inputs:
  input_file:
    type: uri_file
    mode: ro_mount

outputs:
  output_dir:
    type: uri_folder
    mode: rw_mount

jobs:
  preprocessing:
    type: command
    component: components/preprocess.yml
    inputs:
      input_preprocessing: ${{parent.inputs.input_file}}
    outputs:
      output_preprocessing: ${{parent.outputs.output_dir}}
    compute: azureml:cpu-cluster

  training:
    type: command
    component: components/train.yml
    inputs:
      input_training: ${{parent.jobs.preprocessing.outputs.output_preprocessing}}
    outputs:
      output_training: ${{parent.outputs.output_dir}}
    compute: azureml:gpu-cluster

  export:
    type: command
    component: components/export.yml
    inputs:
      input_export: ${{parent.jobs.training.outputs.output_training}}
    outputs:
      output_export: ${{parent.outputs.output_dir}}
    compute: azureml:gpu-cluster
```

I'm invoking the usual way:

```python
def start(self, input_file: str, output_dir: str) -> str | None:
        inputs = {
            "input_file": Input(
                type=AssetTypes.URI_FILE, path=self.mlclient.get_uri(input_file)
            ),
        }
        outputs = {
            "output_dir": Output(
                type=AssetTypes.URI_FOLDER, path=self.mlclient.get_uri(output_dir)
            ),
        }
        job = self.mlclient.invoke_job(
            app_settings.AZUREML_NERFSTUDIO_ENDPOINT, inputs=inputs, outputs=outputs
        )

        return job.name
```

**Comment by emepetres** [comment]
So I managed to fix the issue by creating three outputs (that are really the same). Weird, but it works (see below). I'm closing the issue as I have a workaround, anyways I think this worked in the past and is at least a weird behavior.

```yaml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: nerfstudio_aas
display_name: Nerfstudio AAS Component
type: pipeline

inputs:
  input_file:
    type: uri_file
    mode: ro_mount

outputs:
  output_preprocessing_dir:
    type: uri_folder
    mode: rw_mount
  output_training_dir:
    type: uri_folder
    mode: rw_mount
  output_export_dir:
    type: uri_folder
    mode: rw_mount

jobs:
  preprocessing:
    type: command
    component: components/preprocess.yml
    inputs:
      input_preprocessing: ${{parent.inputs.input_file}}
    outputs:
      output_preprocessing: ${{parent.outputs.output_preprocessing_dir}}
    compute: azureml:gpu-cluster

  training:
    type: command
    component: components/train.yml
    inputs:
      input_training: ${{parent.jobs.preprocessing.outputs.output_preprocessing}}
    outputs:
      output_training: ${{parent.outputs.output_training_dir}}
    compute: azureml:gpu-cluster

  export:
    type: command
    component: components/export.yml
    inputs:
      input_export: ${{parent.jobs.training.outputs.output_training}}
    outputs:
      output_export: ${{parent.outputs.output_export_dir}}
    compute: azureml:gpu-cluster
```
